### ISSUE TITLE
[Feature Request] batch restore savegames?

### ISSUE THREAD

**Issue by Luro02** [FlagBrew/Checkpoint#169]
## Batch restore savegames:
* [ ] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [x] Feature request

### Why?
Currently there is only a batch backup feature in checkpoint, that is really helpful to back-up my save-games, but how do I get them back on my switch? I don't want to install all the games again just to restore my saves, and I don't know what might happen in the future, my sdcard stops working? or Checkpoint no longer supports the old folder names?, therefore I'd love to have a batch restore function similar to the batch backup.

Thanks :)

**Comment by BernardoGiordano** [comment]
To be honest, I don't understand what's the issue here.

> I don't want to install all the games again just to restore my saves

How would you restore saves without having the game installed?

> my sdcard stops working?

That's why you should be actively copying your SD card to a mass storage device too.

> Checkpoint no longer supports the old folder names

You move the backups as well.

> I'd love to have a batch restore function similar to the batch backup

Batch restore is unfeasible. Backing up is a 1-1 operation where Checkpoint exactly knows which save to backup. Restore operation is a N-1 operation, and it doesn't know which save to restore from your list.
