### ISSUE TITLE
Switch version asking me not to run it as an applet

### ISSUE THREAD

**Issue by GuyInDogSuit** [FlagBrew/Checkpoint#248]
**Describe the bug**
Screen is red and warns me not to run it as an applet. 

**To Reproduce**
1. Go to Album.
2. Click on Checkpoint.
3. See error message.

**Expected behavior**
Checkpoint used to load up just fine without this mesage.

**Switch:**
- Entrypoint: Album
- System version: 8.1.0
- Checkpoint version: 3.7.2
- SD Card Filesystem: exFAT
- Result code (if available): none

**Additional context**

**Comment by piepie62** [comment]
Hold R while launching a game to launch the homebrew menu instead of through the album. If that doesn't work, switch away from your shitty CFW to Atmosphère

**Comment by GuyInDogSuit** [comment]
You could have simply stated such without throwing in the "shitty CFW" comment. Keep opinions like that to yourself.

**Comment by fennectech** [comment]
SXOS IS a shitty cfw because  
1. They steal code from atmosphere. With zero credit  
2. They cant Even be timely about it.  Being so out of date that alot of stuff doesnt work with it becasue stuff thats been in all the free alternative for months hasent been put into theirs

3. Piracy is illegal and immoral
4. They steal nintendo code too
5. They (used to) brick consoles  (That code has only been disabled. Not removed). 
7 they refuse to publish the source code allowing others to improve their work (and something they by all rights are obligated to because they use GPL code)

**Comment by GriffinG1** [comment]
7 - The first version of emunand they released wrote to the sd card so much that it was all but guaranteed to corrupt.

**Comment by GuyInDogSuit** [comment]
Don't care what your logic is for it, your opinion doesn't matter and isn't called for.

**Comment by piepie62** [comment]
That is the official opinion of FlagBrew, and will remain as such for the foreseeable future. There is *literally* no good in SXOS besides what they stole from Atmosphère
