### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by realdealxkd** [FlagBrew/Checkpoint#337]
Using cheats on pokemon x y oras  

Start any pokemon game
Use any cheat 
Walk around for a minute or 2
You get arm11 error 

Hopefully gets fixed soon or a new update gets put out

I have a 3ds Xl
Latest firmware on ds using luma 
Checkpoint is also latest version 

You can literally use any cheat on any of the pokemon games and you'll get the same result. I thought it was because I used ntr with checkpoint but I tested it, and you still get the arm11 error no matter what.

**Comment by JourneyOver** [comment]
1. This is the wrong place to report this, use sharkive repository for cheat issues.

2. This could be due to you either trying with codes that are not made for the version of the game you are running (running 1.2 while trying to use codes made for 1.1 or below) or this could be due to a kernel bug. Luma's cheat engine would need to be redesigned to fix this, which would cause another bug elsewhere. As such, there is no solution to this problem at this time besides using another console.
