### ISSUE TITLE
Crash when trying to use cheats on Pokémon Ulta sun

### ISSUE THREAD

**Issue by ahuby09** [FlagBrew/Checkpoint#338]
Hi keep getting crashes when ever I try to use any cheat on ultra sun here is the error
![15860400496772763227327775691279](https://user-images.githubusercontent.com/7256690/78462822-bbd6a100-76cd-11ea-992b-c14b4fe40137.jpg)

**Comment by JourneyOver** [comment]
1. This is the wrong place to report this, use sharkive repository for cheat issues.

2. This could be due to you either trying with codes that are not made for the version of the game you are running (running 1.2 while trying to use codes made for 1.1 or below) or this could be due to a kernel bug. Luma's cheat engine would need to be redesigned to fix this, which would cause another bug elsewhere. As such, there is no solution to this problem at this time besides using another console.
