### ISSUE TITLE
Application crashes on Atmosphere 14.4

### ISSUE THREAD

**Issue by dothackjhe** [FlagBrew/Checkpoint#375]
**Describe the bug**
Running Checkpoint 3.7.4 from the Homebrew Menu causes the system to crash.

**To Reproduce**
1. Go to Hbmenu via Album
2. Click on Checkpoint (version 3.7.4.)
3. System crashes

**Expected behavior**
Instead of making the app work, the bug causes the system to crash.

**Switch:**
- Entrypoint: Hbmenu 3.3.0
- System version: 10.0.2
- Checkpoint version: 3.7.4
- SD Card Filesystem: ExFAT

**Comment by GriffinG1** [comment]
![D28FE3BE-1063-4919-805C-0EA0D36C2890](https://user-images.githubusercontent.com/28538707/97038949-d61c8300-1528-11eb-9832-a8980d4fe1ce.jpeg)

**Comment by Ninoninixion** [comment]
**Describe the bug**:

Running Checkpoint 3.7.4 from the Homebrew Menu causes the system to freeze, then crash response after a few minutes. Only happening few days after last usage (when first installed, worked perfectly) 

**To Reproduce**:

Steps to reproduce the behavior:

Go to Hbmenu via Album _(AND Applet [Pressing 'R'] mode)_
Click on Checkpoint (version 3.7.4.)
System freezes, then black screens few moments later _(Switch unresponsive)_

**Expected behavior:**

Checkpoint would (at first) work in and out of 'Applet mode' Then tried it a few days later, for it to freeze, then lock up system and even (twice) nearly corrupts SD card _(OS Fatal Error When booting up)_.

**Switch:**

Hekate 5.3.3
Atmosphere 14.4|E
Hbmenu 3.3.0 - _Entry Point_
System version: 10.2.0
Checkpoint version: 3.7.4
SD Card Filesystem: FAT32
