### ISSUE TITLE
Checkpoint keep automaticly closing after launching

### ISSUE THREAD

**Issue by Cheesing-Jade** [FlagBrew/Checkpoint#456]
**Describe the bug**
when I try to start checkpoint from hbmenu it just closes then goes back to hbmenu

**To Reproduce**
1. Go to 'hbmenu'
2. Click on 'checkpoint'
3. goes back to hbmenu

**Expected behavior**
checkpoint opening normally

**Switch:**
- Entrypoint: hbmenu (album)
- System version: 14.0.0
- Checkpoint version: 3.8.0
- SD Card Filesystem: fat32
- Result code (if available):

**Additional context**
AMS: 1.3.0
HATS: 1.3.0

**Comment by GriffinG1** [comment]
#450 duplicate.

**Comment by Cheesing-Jade** [comment]
in the original post it is written that if the issue is still occuring to open a new issue. The issue is still occuring and that's why I oppened an issue.

**Comment by GriffinG1** [comment]
#450 also says not to use applet mode, which is what you're using when accessing via album. This is not the issue recurring.

**Comment by solleo1989** [comment]
Your reproduce description didn't give us anything to addresss your issue, and therefore nobody's gonna figure out the root casue. 
As Greiffin said, due to the lack of memory support, "applet mode" is not supported anymore. You have to open the homebrew menu by holding L and enter the gaming icon, and then Checkpoint will work.

If you still use the "Album" applet mode, it will keep occur for sure.

**Comment by GriffinG1** [comment]
Locking as resolved, #450 tells them the same thing and we shouldn't be spoon feeding users.
