### ISSUE TITLE
[Question] how do I build from source?

### ISSUE THREAD

**Issue by MonfGeiger** [FlagBrew/Checkpoint#467]
Yes, i did install devkitpro (for windows), left all box choices checkmarked, did both the pacman commands for 3ds and switch, i got all dependencies that i need (hopefully), and i cd to the master folder i downloaded, and hoped that just running make would do it, but apparently it isnt that simple

for a very amateur 5head here, what command arg do i need to use to build this homebrew from source without messing it up?

**Comment by piepie62** [comment]
You provided exactly zero information about the nature of the error you encountered; `make` is the correct command. What seems most likely to me is that you didn't check out submodules or something like that.

**Comment by MonfGeiger** [comment]
someone in the fortheusers discord said the same thing, so i grabbed git, cloned the repository, cd'd to the checkpoint folder, and ran make switch and i got the .nro file, tested it. it runs fine and works fine, although the Backup _[_L_]_ button still glitches out weirdly, it performs just the same as the current 3.8.0 version does

apologies for my 7head moment, take from my last comment about the L button as a mini bug report, please and thank you

**Comment by impeeza** [comment]
Hi, I know is Closed, and the way the issue was open is incomplete rendering wrong, I also try to compile using MSYS (MinGW64) on windows, and find some missing instructions on the Readme.md.  For a successful compile binaries I had to follow the next steps:

1. Install a Working DevKitPro environment, you have two options:
- Using the devkitProUpdater-3.0.3.exe from https://devkitpro.org/wiki/Getting_Started (redirected to https://github.com/devkitPro/installer/releases)
- Install Msys using the latest release (https://github.com/msys2/msys2-installer/releases) and then follow the instructions on https://devkitpro.org/wiki/devkitPro_pacman to install devKitPro.
2. After executing several times `pacman -Syu --noconfirm` until you get "Noting To Do", Install the base packages using: `pacman -Syu --noconfirm mingw-w64-x86_64-ccache make git pkg-config mingw-w64-x86_64-gcc mingw-w64-x86_64-ccache`.
3. Install packages for Switch and 3DS developement `sudo dkp-pacman -Syu --noconfirm 3ds-dev switch-dev devkitARM devkitA64`
4. Again make sure you are up to date: `pacman -Syu --noconfirm`
5. Then install the packages listed on the Readme.md for 3ds: `sudo dkp-pacman -S libctru citro3d citro2d tex3ds 3ds-bzip2`
6. and Switch: `sudo dkp-pacman -S libnx switch-pkg-config switch-freetype switch-libpng switch-libjpeg-turbo switch-sdl2 switch-sdl2_image switch-sdl2_ttf`
7. Some of the omissions on readme.md are the need of the next tools:
- smdhtool, is part of devkitARM
- makerom, you can get it from: https://github.com/3DSGuy/Project_CTR/releases/tag/makerom-v0.18.3 and then copy to /opt/devkitpro/tools/bin
- bannertool, you can get it from: https://github.com/Steveice10/bannertool/releases and then copy to /opt/devkitpro/tools/bin

Now you can clone the repo:
`git clone --recursive https://github.com/FlagBrew/Checkpoint.git`

Set the DevKitPro environment variables:
```
export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITPPC=${DEVKITPRO}/devkitPPC

export PATH=${DEVKITPRO}/tools/bin:$PATH
```
and now you can run
`make` for get 3ds and Switch binaries,
or `make 3ds` for 3ds only
or `make switch` for Switch one.
